name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  auto-versioning:
    name: Auto Versioning Commit
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: python:latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout Current branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.app-token.outputs.token }}

      - run: echo "hello world" >> README.md

      - name: Update Ownership in Repository
        run: git config --global --add safe.directory "/__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}"
